analyzer:
  errors:
    unnecessary_brace_in_string_interps: ignore
    unnecessary_string_interpolations: ignore
    use_build_context_synchronously: ignore
  exclude:
    - test
    - dev
    - templates
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - public_member_api_docs
