name: 'example'
description: 'A new Flutter project.'
publish_to: 'none'
version: '0.0.0'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  cupertino_icons: '^1.0.2'
  general: 
    path: '../'
  media_kit_video: '^1.2.4'
  local_auth: '^2.2.0'
  telegram_client: '^0.8.22'
  general_lib: '^0.0.44'
  general_lib_flutter: '^0.0.25'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: 
  uses-material-design: true
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
