name: 'example'
description: 'A new Flutter project.'
publish_to: 'none'
version: '0.0.0'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  cupertino_icons: '^1.0.2'
  general_flutter: '^0.0.23'
  media_kit_video: '^1.2.4'
  local_auth: '^2.2.0'
  geolocator: '^11.0.0'
  baseflow_plugin_template: '^2.1.2'
  telegram_client: '^0.8.19'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: 
  uses-material-design: true
dependency_overrides: 
  pointycastle: '3.8.0'
