name: 'general_project'
description: 'General library For Make Your Coding or Project More Easy'
version: '0.0.27'
repository: 'https://github.com/azkadev/general'
homepage: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues '
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.63'
  http: '^1.2.2'
  mason_logger: '^0.3.1'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.3'
  yaml_writer: '^2.0.1'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
