name: 'general_project'
description: 'General library For Make Your Coding or Project More Easy'
version: '0.0.23'
repository: 'https://github.com/azkadev/general'
homepage: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues '
documentation: 'https://youtube.com/@azkadev'
funding: 
  - 'https://github.com/sponsors/azkadev'
environment: 
  sdk: '^3.2.3'
dependencies: 
  general_lib: '^0.0.40'
  http: '^1.2.1'
  mason_logger: '^0.2.11'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: 'any'
  yaml_writer: 'any'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
