name: 'general'
description: 'A sample command-line application.'
version: '0.0.20'
repository: 'https://github.com/azkadev/general'
environment: 
  sdk: '^3.2.3'
dependencies: 
  general_lib: '^0.0.27'
  http: '^1.2.1'
  mason_logger: '^0.2.11'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: 'any'
  yaml_writer: 'any'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
homepage: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues '
documentation: 'https://youtube.com/@azkadev'
funding: 
  - 'https://github.com/sponsors/globalcorporation'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
