name: 'general_flutter'
description: 'General library For Make Your Coding or Project More Easy'
version: '0.0.0'
homepage: 'https://github.com/azkadev/general'
repository: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues '
documentation: 'https://youtube.com/@azkadev'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  awesome_notifications: '^0.9.3+1'
  file_picker: '^8.0.3'
  flutter_background: '^1.2.0'
  flutter_tts: '^4.0.2'
  general: '^0.0.23'
  general_dart: '^0.0.23'
  general_lib: '^0.0.42'
  path: '^1.8.3'
  permission_handler: '^11.3.1'
  safe_device: '^1.1.6'
  speech_to_text: '^6.6.0'
  universal_io: '^2.2.2'
  sim_card_info: '^1.0.1'
  sms_flutter: '^0.0.0'
  general_lib_flutter: '^0.0.22'
  media_kit: '^1.1.10+1'
  media_kit_video: '^1.2.4'
  local_auth: '^2.2.0'
  wakelock_plus: '^1.2.5'
  battery_plus: '^6.0.1'
  camera: '^0.11.0'
  camera_windows: '^0.2.1+8'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: null
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
