name: 'sms_flutter'
description: 'This is an SMS library for Flutter. Its allow to send, receive, query sms messages, sms delivery and query contacts info in Android, and only sending in IOS & Web.'
version: '0.0.0'
environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.20.0'
dependencies:
  flutter:
    sdk: 'flutter'
  flutter_web_plugins:
    sdk: 'flutter'
  plugin_platform_interface: '^2.1.8'
  url_launcher: '^6.3.1'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^4.0.0'
flutter:
  plugin:
    platforms:
      android:
        package: 'com.elyudde.sms_flutter'
        pluginClass: 'SmsFlutterPlugin'
      ios:
        pluginClass: 'UssdAdvancedPlugin'
      web:
        pluginClass: 'SmsFlutterPlugin'
        fileName: 'sms_flutter_web.dart'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
