include: package:lints/recommended.yaml
analyzer:
  exclude:
    - dev/
    - template/
    - test/
    - example/
    - lib/flutter/device
    - lib/api/file
    - test
    - dev
    - templates
    - lib/api/file/
linter:
  rules:
    - public_member_api_docs
