name: 'general'
description: 'General library For Make Your Coding or Project More Easy'
version: '0.0.30'
homepage: 'https://github.com/azkadev/general'
repository: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues '
documentation: 'https://youtube.com/@azkadev'
funding: 
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
executables: 
  general: 'general'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  general_lib: '^0.0.46'
  # desktop_notifications: '^0.6.3'
  media_kit: '^1.1.1'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  mason_logger: '^0.3.1'
  html: 'any'
  collection: '^1.18.0'
  yaml: '^3.1.2'
  yaml_writer: '^2.0.1'
  flutter: 
    sdk: 'flutter'
  file_picker: '^8.1.4'
  flutter_background: '^1.3.0+1'
  flutter_tts: '^4.2.0'
  permission_handler: '^11.3.1'
  speech_to_text: '^7.0.0'
  sim_card_info: '^1.0.2'
  general_lib_flutter: '^0.0.27'
  media_kit_video: '^1.2.5'
  local_auth: '^2.3.0'
  wakelock_plus: '^1.2.8'
  camera: '^0.11.0+2'
  camera_windows: '^0.2.6+1'
  # gamepads: '^0.1.3'
  image: '^4.3.0'
dev_dependencies: 
  lints: '^4.0.0'
  test: 'any'
dependency_overrides: 
  pointycastle: '3.8.0'
