name: 'general'
description: 'General library For Make Your Coding or Project More Easy'
version: '0.0.26'
homepage: 'https://github.com/azkadev/general'
repository: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues '
documentation: 'https://youtube.com/@azkadev'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  general_lib: '^0.0.43'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
dependency_overrides: 
  pointycastle: '3.8.0'
