name: 'general'
description: 'General Library for help you integrate any package commong used like permission, and many more only use one library'
version: '0.0.43'
homepage: 'https://github.com/azkadev/general'
repository: 'https://github.com/azkadev/general'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'general'
  - 'system'
  - 'device'
  - 'plugin'
  - 'media'
executables:
  general: 'general'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.60'
  media_kit_fork: '^0.0.1'
  path: '^1.9.0'
  io_universe: '^0.0.4' 
  html: 'any'
  collection: '^1.19.0'
  yaml: '^3.1.3'
  yaml_writer: '^2.0.1'
  flutter:
    sdk: 'flutter'
  file_picker: '^8.1.4'
  flutter_background: '^1.3.0+1'
  flutter_tts: '^4.2.0'
  permission_handler: '^11.3.1'
  speech_to_text: '^7.0.0'
  general_lib_flutter: '^0.0.40'
  media_kit_video_fork: '^0.0.1'
  wakelock_plus: '^1.2.8'
  camera: '^0.11.0+2'
  camera_windows: '^0.2.6+1'
  image: '^4.3.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
