name: 'general'
description: 'General library For Make Your Coding or Project More Easy'
version: '0.0.29'
homepage: 'https://github.com/azkadev/general'
repository: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues '
documentation: 'https://youtube.com/@azkadev'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
executables: 
  general: 'general'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  general_lib: '^0.0.44'
  desktop_notifications: '^0.6.3'
  media_kit: '^1.1.1'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  mason_logger: '^0.2.15'
  html: 'any'
  collection: 'any'
  yaml: '^3.1.2'
  yaml_writer: '^2.0.0'
  flutter: 
    sdk: 'flutter'
  file_picker: '^8.1.2'
  flutter_background: '^1.3.0+1'
  flutter_tts: '^4.0.2'
  permission_handler: '^11.3.1'
  safe_device: '^1.1.8'
  speech_to_text: '^7.0.0'
  sim_card_info: '^1.0.2'
  sms_flutter: '^0.0.0'
  general_lib_flutter: '^0.0.25'
  media_kit_video: '^1.2.5'
  local_auth: '^2.3.0'
  wakelock_plus: '^1.2.8'
  battery_plus: '^6.0.3'
  camera: '^0.11.0+2'
  camera_windows: '^0.2.5'
  gamepads: '^0.1.2'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
dependency_overrides: 
  pointycastle: '3.8.0'
