name: 'general_server'
description: 'A sample command-line application.'
version: '0.0.20'
homepage: 'https://github.com/azkadev/general'
repository: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues '
documentation: 'https://youtube.com/@azkadev'
funding: 
  - 'https://github.com/sponsors/globalcorporation'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.2.3'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
